global:
  remote_project_root: "."
  local_project_root: "."
  user: "root"
  local_data_dir: "analysis/data"
  nodes:
    receiver_ip: "127.0.0.1"
    sender_ip: "127.0.0.1"
    receiver_iface: "lo"

benchmarks:
  - name: "threaded"
    enabled: true
    receiver:
      binary: "receiver_threaded"
      cpu_affinity: 3
      batch_size: [16,32]  
      processing_time_ns: 10000
    sender:
      mode: "steady"
      duration_sec: 5
      rates_pps: [1000,5000,10000,25000,50000,75000,100000, 500000, 1000000]
      payload_size: 64
  - name: "baseline"
    enabled: true
    receiver:
      binary: "receiver_baseline"
      cpu_affinity: 3
      processing_time_ns: 10000
    sender:
      mode: "steady"
      duration_sec: 5
      rates_pps: [1000,5000,10000,25000,50000,75000,100000, 500000, 1000000]
      payload_size: 64



